### PR TITLE
Add client method to include remoteHost when opening tcp tunnel

### PR DESCRIPTION
**Pull request by destryteeter**

### CODE REVIEW

**Comment by destryteeter** [comment]
Any thoughts on when this can be merged in?

**Review by ghost — APPROVED** [review]

**Comment by destryteeter** [comment]
Thanks!  Will you update the framework referenced in the pod spec too please?

https://downloads.nabto.com/assets/nabto-ios-client/#{s.version}/NabtoClient.framework.zip

**Comment by nabto** [comment]
Sorry about the delay. The pod spec has been updated and the updated client bundle pushed.

**Comment by destryteeter** [comment]
Great, looks good

**Pull request merged**
